version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-module"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j8jgzrngjsm8"
s3_prefix = "user-module"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"dev\" IdentityPoolName=\"user-module-identity-pool\" ProjectName=\"user-module\" Region=\"ap-northeast-1\" Tag=\"aws-aurora-vpc\" AuroraClusterIdentifier=\"water-aurora-cluster\" AuroraInstanceIdentifier=\"water-aurora-instance\" AuroraDBName=\"waterauroradb\" AuroraDBProxyName=\"waterauroradb-proxy\" VPCSubnetIds=\"subnet-529b2879,subnet-7ce74f34,subnet-f94e54a2\" DbSubnetGroupName=\"water-db-subnet-group\""
image_repositories = []
