version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-module"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j8jgzrngjsm8"
s3_prefix = "user-module"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\" ProjectName=\"user-module\" TableName=\"pwsp_revenue_system\" Region=\"ap-northeast-1\" Tag=\"aws-aurora-vpc\" KmsKeyId=\"76469d22-c205-4275-b7dd-33cad075b0ce\" DbName=\"usermodule\""
image_repositories = []
