version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-module"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j8jgzrngjsm8"
s3_prefix = "user-module"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\" ProjectName=\"user-module\""
image_repositories = []
